Makefile improvements.
elastic/elasticsearch-rs pull request #142
Opened 2020-09-18 09:42 UTC by sagiegurari

Really cool crate. Trying to help a bit sort out and remove duplications in the makefile.

* Default message is now in duckscript so its same code for all platforms. no need for code duplication.
* start/stop search task has a base task so common code is there.
* start/stop search task no longer has a windows specific implementation
* Move CI env var which isn't supported for all CI vendors to CARGO_MAKE_CI which supports all.

Few questions/comments

1. I couldn't test it properly. i'm working on gitpod and i can't run docker. would love some help testing this.
2. why did you have the windows specific overrides? 
i understand why you need those when using script (that's why i converted to command+args which support var value replacement) but for start/stop elasticsearch tasks i'm not sure why it was needed.
I don't have a windows machine to test (again need help with that as well) so i would love to understand more why your original tasks didn't work.
because it looks like for those you simply also defined STACK_VERSION and TEST_SUITE on the command, but those env vars are already set.

2020-09-21 00:01 UTC, russcam requested changes
Thanks for opening @sagiegurari, and thank you also for cargo make, it's exactly what I was looking for 😄 I've left some comments.

Would you mind [signing the CLA](https://www.elastic.co/contributor-agreement), so that this PR could eventually be pulled in?

2020-09-23 15:16 UTC, sagiegurari commented on Makefile.toml
> +script = { file = "./.ci/run-elasticsearch.sh" }
thanks for the info. i'll revert this one, or think of another way.

2020-09-23 15:16 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-09-23 15:18 UTC, sagiegurari commented on Makefile.toml
> +condition = { env_set = [ "ELASTICSEARCH_URL" ], env_false = ["CARGO_MAKE_CI"] }
no need to touch that shell. ci_info crate will detect its CI env if you did CI=true.
than cargo make will set CARGO_MAKE_CI=true
so its fine.
the advantage of this, is that you can later on support other CI providers that do not set the CI env var.

2020-09-23 15:32 UTC, sagiegurari commented on Makefile.toml
> +    echo - CARGO_MAKE_CI (default not set): set when running on CI to determine whether to start Elasticsearch and format test output as JSON
actually this should stay CI and not CARGO_MAKE_CI
its automatically set for you based on the env.

2020-09-23 15:39 UTC, sagiegurari commented on Makefile.toml
>      echo - CI (default not set): set when running on CI to determine whether to start Elasticsearch and format test output as JSON
sorry, keeping it CI as CARGO_MAKE_CI is automatically defined for you by cargo-make internally with true/false value.

2020-09-23 16:37 UTC, sagiegurari commented
* signed the CLA
* few updates per comments (double check me)
* merged changes
* improved instructions printing per platform after merges

2020-10-01 02:21 UTC, russcam requested changes
Thanks @sagiegurari, I just left one small suggestion but otherwise LGTM 👍  Thank you for your conribution!

2020-10-01 05:30 UTC, sagiegurari commented on Makefile.toml
> +    end
oh ok, so you want the actual value. for some reason (my mistake) i thought you wanted to show what env var it is :)
i'll fix that.

2020-10-01 11:03 UTC, russcam commented on Makefile.toml
> +    end
Yeah, the actual value is what we want. Sorry for any confusion 😄

2020-10-06 08:35 UTC, sagiegurari commented
@russcam I think everything is handled, but can you double check?

2020-10-07 06:34 UTC, russcam approved these changes
LGTM, thanks @sagiegurari 👍

2020-10-07 06:36 UTC, merged